### ISSUE TITLE
[Event Service] Replicate events from Discovery tab recommended users.

### ISSUE THREAD

**Issue by boreq** [planetary-social/nos-event-service#53]
~~Nos has a list of suggested contacts. We should replicate their events as well.~~

In addition to connecting the nos users to the event service, we should also connect the accounts of people who we recommend on the Discovery tab. The list of people we recommend can be found here: https://www.notion.so/nossocial/Nos-Featured-Users-7ab93222b819477fb87be585d18d6a39

**Comment by setch-l** [comment]
Closing as we updated the Discover tab
