### ISSUE TITLE
Sometimes we fail to push events to the relay and the queue length goes up

### ISSUE THREAD

**Issue by boreq** [planetary-social/nos-event-service#68]

**Comment by dcadenas** [comment]
I noticed this now, starting on friday and during the weekend. I don't have a good explanation for the queue increase yet but I added 2 PRs for hunting more info and validate some hunches:
https://github.com/planetary-social/nos-event-service/pull/74
https://github.com/planetary-social/nos-event-service/pull/75

**Comment by dcadenas** [comment]
I also increase the relay concurrent requests value, although I think that didn't affect the queue.

**Comment by dcadenas** [comment]
I noticed we were ignoring NOTICE messages asking us to slow down so we were hitting rate limits from our own relay and some of the other relays too. I added a change through https://github.com/planetary-social/nos-event-service/pull/80 that is already deployed and I'm currently evaluating

**Comment by dcadenas** [comment]
The queue seems much healthier now after dealing with rate limit warnings from both CLOSE and NOTICE messages. I will close this ticket for now and may reopen if I see any unexpected bump in the next days
